import Link from 'next/link';

export default function SecurityPage() {
  return (
    <div className="landing-premium" style={{ minHeight: '100vh', display: 'flex', flexDirection: 'column' }}>
      <nav className="premium-nav" style={{ position: 'relative', background: 'transparent' }}>
        <div className="premium-logo">
          <Link href="/" className="premium-logo" style={{ display: 'flex', alignItems: 'center' }}>
            <img src="/retriqo-logo.svg" alt="Retriqo" style={{ height: '28px' }} />
          </Link>
        </div>
      </nav>
      
      <main className="premium-container" style={{ flex: 1, padding: '120px 5vw', maxWidth: '800px' }}>
        <div className="section-tag mono" style={{ marginBottom: '2rem' }}>{'// Compliance'}</div>
        <h1 className="section-title" style={{ marginBottom: '4rem', fontSize: '3rem' }}>Security Practices</h1>
        
        <div style={{ color: 'var(--text-muted)', lineHeight: 1.6, fontSize: '1.1rem', display: 'flex', flexDirection: 'column', gap: '2rem' }}>
          <section>
            <h2 style={{ color: 'var(--text-main)', fontSize: '1.5rem', marginBottom: '1rem', fontWeight: 500 }}>Cryptographic Foundation</h2>
            <p>All routing links generated by Retriqo are cryptographically signed. It is computationally infeasible to guess or brute-force a valid document identifier without possessing the physical QR anchor. Data at rest is encrypted using AES-256-GCM standards.</p>
          </section>
          
          <section>
            <h2 style={{ color: 'var(--text-main)', fontSize: '1.5rem', marginBottom: '1rem', fontWeight: 500 }}>Access Revocation</h2>
            <p>Security is stateful. When an administrator revokes access or a document reaches its expiry threshold, the revocation propagates through the global edge network in less than 50 milliseconds. Subsequent scans will immediately drop the connection at the edge node.</p>
          </section>
          
          <section>
            <h2 style={{ color: 'var(--text-main)', fontSize: '1.5rem', marginBottom: '1rem', fontWeight: 500 }}>Vulnerability Reporting</h2>
            <p>We take the security of our industrial routing network seriously. If you believe you have discovered a vulnerability, please contact our security team immediately. We operate a responsible disclosure program and will respond to valid reports within 24 hours.</p>
          </section>
        </div>
      </main>
    </div>
  );
}
